// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"io"
	"sync"
)

type Reader struct {
	ReadStub        func([]byte) (int, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		arg1 []byte
	}
	readReturns struct {
		result1 int
		result2 error
	}
	readReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Reader) Read(arg1 []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (fake *Reader) ReadCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *Reader) ReadCalls(stub func([]byte) (int, error)) { _ = "STUB: not implemented"; return }

func (fake *Reader) ReadArgsForCall(i int) []byte { _ = "STUB: not implemented"; return nil }

func (fake *Reader) ReadReturns(result1 int, result2 error) { _ = "STUB: not implemented"; return }

func (fake *Reader) ReadReturnsOnCall(i int, result1 int, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *Reader) Invocations() map[string][][]interface{} { _ = "STUB: not implemented"; return nil }

func (fake *Reader) recordInvocation(key string, args []interface{}) {
	_ = "STUB: not implemented"
	return
}

var _ io.Reader = new(Reader)
